service: serverless-webpack-circle-boilerplate

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
